import Head from 'next/head'

import MainContainer from "../components/container/mainContainer"
import Registration from "../components/registration/registration"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainContainer>
          <Registration/>
        </MainContainer>
      </main>
    </>
  )
}
